Update docker-compose.yml (#2109)
* Update docker-compose.yml

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mealie.environment.WEB_GUNICORN contains true, which is an invalid type, it should be a string, number, or a null

* Update docker-compose.yml

Also fix SMTP settings, since they aren't in array format as in mealie-frontend.

* Once more, ironing out a few minor issues.

Server status reported this, I think this is the correct value, but I'm happy to revert and/or update the value as needed.

* Revert previous two commits

Per https://github.com/hay-kot/mealie/pull/2109#pullrequestreview-1294610637

* Stray newline

Missed a stray newline that was inadvertently added.